services:
  - type: web
    name: search_analytics_backend
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: search_analytics_backend
          property: connectionString
