# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: search_analytics_development

test:
  <<: *default
  database: search_analytics_test

production:
  <<: *default
  database: search_analytics_production
